### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by elliottsj** [elliottsj/angular-chrome-messaging#3]
Need to add usage instructions to README.md, or the wiki.

**Comment by ricardocasares** [comment]
Hey @elliottsj would be really nice to have some docs, I can help you if we have a chance to talk sometime about the usage. I was looking for something like this, good work!

**Comment by elliottsj** [comment]
I've added some usage info to the README and added an example as well. Sorry I haven't given this project much love lately since I haven't been using it, but I'm glad it's useful to others!

**Comment by ricardocasares** [comment]
You are awesome!
